// ⚠️  PLACEHOLDER — This file must be generated by the FlutterFire CLI.
//
// Run the following commands to generate this file:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=reimbursement-hexa
//
// The generated file will replace this placeholder.
// Do NOT commit real API keys; use .gitignore or secret management.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web is not a target platform.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Replace values below after running `flutterfire configure` ─────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ANDROID_API_KEY',
    appId: 'REPLACE_WITH_ANDROID_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'reimbursement-hexa',
    storageBucket: 'reimbursement-hexa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'reimbursement-hexa',
    storageBucket: 'reimbursement-hexa.appspot.com',
    iosBundleId: 'REPLACE_WITH_IOS_BUNDLE_ID',
  );
}
